github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31666537323430656463343265646365643561333466386335343566663836373138333230373037
  6239613732393661356438666236373436633561613465320a343236326633336262643866636439
  36633661363237653062393937376531303932323636376236353433313737376436623338313830
  6363393330313537330a363462613035646439303837323838636438353633316163343937306136
  36356432613630613061656637393763353231326238626561333637323235653262396433303361
  6530343462623361663739383738366565386162376165303330
 ## virtual hardware specs
cores: 4
cpulimit: 4
cputype: host
maxmemory: 4096
memory: 16384
## root disk
diskpool: nvme_pool
rootsize: 50
## options
agent: enabled=1
protection: true
##resource pool
pool: Lothlorien
# List of encrypted dot-paths
encrypted_keys:
- github_token
