github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36346339313434346263653564316432646139383034303133303933356537653731666363363066
  3363366266363564646535653433363164623237333832660a373630333766393033353036323137
  33323232643463323361343435383561373135316638303465373838366132383333646634666262
  3333336334386137370a626633373233613131666661373831306232643561333633636362326130
  34396438326430303231336366346538333939366134633566333231356663306433636231623835
  3732376464363437373635346433626163636331306661366539
kubeapiaddress: https://bombadil.local:16443
vault_address: https://bombadil.local:8200
## virtual hardware specs
cores: 8
cpulimit: 8
cputype: host
vmballoon: 4096
vmmemory: 16384
## root disk
diskpool: ssd_pool
rootsize: 50
## options
agent: enabled=1
protection: false
##resource pool
pool: Mirkwood
# List of encrypted dot-paths
encrypted_keys:
- github_token
