## virtual hardware specs
cores: 1
memory: 1024
## root disk
diskpool: ssd_pool
rootsize: 5
## options (not sure why there is not one for 'protection'?)
unprivileged: true
onboot: true
## resource pool
pool: Lothlorien