## virtual hardware specs
cores: 4
cpulimit: 4
cputype: host
maxmemory: 4096
memory: 16384
## root disk
diskpool: nvme_pool
rootsize: 50
## options
agent: enabled=1
protection: true
##resource pool
pool: Lothlorien