github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38356430323538653965313532626464353532653164373338643439373765623132623264313363
  3632613637373634663663303564656537656531656232350a303035643162633831353132313161
  31656236636138623261636166373062356536633931396133643531656238366231346431643966
  6539653837343733340a306132616134376663373439663161353762363136353336646362653536
  64656565336132623763623565363234623664353039386230626637323332313236383061323133
  3764363135346462316466626539336233386338333936613736
## virtual hardware specs
cores: 8
cpulimit: 8
lxcmemory: 16384
## root disk
diskpool: nvme_pool
rootsize: 50
## options (not sure why there is not one for 'protection'?)
unprivileged: true
onboot: true
## resource pool
pool: Valinor
# List of encrypted dot-paths
encrypted_keys:
- github_token
