## root disk
diskpool: ssd_pool
rootsize: 10
## options (not sure why there is not one for 'protection'?)
unprivileged: true
onboot: true
## resource pool
pool: MistyMountains
github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37326230353032656634643136353565376337666537396534313532393036303739376639343339
  3863346639663935643735396335653637353461313839650a636231363766353137336636623661
  39376533313634353231613034626463663235336266343934626262616165616465333039613839
  3639643963343431640a663333316634363466333637623637666634356566343365373637306439
  37666465323665366364643866323634356364306531643432326565383937366666343038393466
  3539653831356234333032663931636238393435633963363034
encrypted_keys:
- github_token
