YOUR_GITHUB_USERNAME: dekeyrej
YOUR_GITHUB_TOKEN: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61663664356630316164633962666634323966643163313738653135363132636437643030316338
  3633333735396637663834376662323739336537306161340a353934646535323335393131323064
  65646330636266656337636465643462656339613631643934353631366266643839646139303132
  3164346636633130390a333237383233363963613161356665393837336533663731616634663132
  33613736386533666664323464323734323635663239333034323136646562396363613565333039
  3036386531366262343732663633653266356362376363383663
YOUR_EMAIL: joedekeyrel@gmail.com
encrypted_keys:
- YOUR_GITHUB_TOKEN
